name: uni_storage_api
description: ""
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  uni_storage_client:
    path: ../../packages/uni_storage_client
  uni_storage_driver_local:
    path: ../../packages/uni_storage_driver_local
  uni_storage_driver_minio:
    path: ../../packages/uni_storage_driver_minio
  yaml: ^3.1.0

dev_dependencies:
  build_runner:
